### ISSUE TITLE
Open Api don't support more that once the same specific tag as property.

### ISSUE THREAD

**Issue by jconcavi** [devonfw/cobigen#490]
Reading the information of how to use an OpenApi file in Cobigen (https://github.com/devonfw/tools-cobigen/wiki/howto_openapi_generation#full-example) do you have an example that the validator mark with errors.

```
SampleData:
      x-component: sampledatamanagement
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          minLength: 0
          description: Name string.
        surname:
          type: string
          description: Surname string.
        age:
          type: integer
          format: int32
          description: Age integer.
        mail:
          type: string
          description: Mail string.
      x-onetoone: RestaurantTable
      x-onetomany: MoreData
      x-onetomany: RestaurantTable
```
To avoid this error I propose to use two diferents implementations, the actual one to have only one relation of the types allowed (as right now) and a second one that permit to define an enum of classes to do the relation with. This must be analized with the issue #485 to see if is feasible.

```
   x-onetomany:
       enum:
       - MoreData
       - RestaurantTable
```
Detail of the error in the swagger editor (http://editor.swagger.io)
![2018-02-20 14_24_15-clipboard](https://user-images.githubusercontent.com/22232540/36426269-cf1f79da-1649-11e8-8573-ea678eb56632.png)
